project:
  type: book

book:
  title: "The Health Informaticist"
  author: "Hants Williams"
  date: "10/28/2024"
  page-footer: 
    left: "Copyright 2024, Hants Williams" 
    right: 
      - icon: github
        href: https://github.com/hantswilliams
  page-navigation: true
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Python"
      chapters:
        - chapters_python/1_basics/hello_world.qmd
        - chapters_python/1_basics/flow_variables.qmd
        - chapters_python/2_types_operators/types.qmd
        - chapters_python/2_types_operators/operators.qmd
        - chapters_python/2_types_operators/comparison_bool_operators.qmd
        - chapters_python/2_types_operators/strings.qmd
        - chapters_python/3_compound_types/lists.qmd
        - chapters_python/3_compound_types/dictionaries.qmd
        - chapters_python/4_control_flow/if.qmd
        - chapters_python/4_control_flow/for.qmd
        - chapters_python/4_control_flow/code_blocks.qmd
        - chapters_python/exercises/exercises_1.qmd
        - chapters_python/5_functions/definition.qmd
        - chapters_python/5_functions/more.qmd
        - chapters_python/exercises/exercises_2.qmd
        - chapters_python/6_local_install/install.qmd
        - chapters_python/6_local_install/local_hello_world.qmd
        - chapters_python/7_files/paths.qmd
        - chapters_python/7_files/read_write.qmd
        - chapters_python/8_modules_packages/modules.qmd
        - chapters_python/8_modules_packages/std_library.qmd
        - chapters_python/9_exceptions/exceptions.qmd
        - chapters_python/exercises/exercises_3.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  live-html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



