project:
  type: book

book:
  title: "The Health Informaticist"
  author: "Hants Williams"
  date: "10/28/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - python.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  live-html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



